#!/usr/bin/env bash

if [ "$#" -ne 1 ]
then
	echo "`basename $0` -- convert images to cowfiles" 2>&1
	echo -e "usage: `basename $0` <file>\n" 2>&1
	exit 1
fi

echo '          $the_cow =<<EOC;'
echo '           $thoughts'
echo '            $thoughts'
echo '             $thoughts'
echo '              $thoughts'
img2xterm $1
echo
echo 'EOC'
